global:
  scrape_interval: 15s  

scrape_configs:
  - job_name: 'flask_app'
    scrape_interval: 5s   
    metrics_path: '/metrics'  # Flask app metrics endpoint
    static_configs:
      - targets: ['web:5000']  # Flask app service name and exposed port
    scheme: http
  
